import { StyleSheet } from 'react-native';

export default StyleSheet.create({
  screen: {
    flex: 1,
    paddingVertical: 12,
  },
  card: {
    backgroundColor: '#23234b',
    borderRadius: 16,
    padding: 16,
    marginHorizontal: 16,
    marginVertical: 8,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 5,
  },
  headerCenter: {
    alignItems: 'center',
    marginBottom: 12,
    gap: 2,
  },
  cardTitle: {
    fontSize: 20,
    fontWeight: 'bold',
    color: '#fff',
  },
  predictButton: undefined,
  predictButtonText: {
    color: '#fff',
    fontWeight: '600',
    fontSize: 14,
  },
  predictionHero: {
    alignItems: 'center',
    paddingVertical: 12,
    gap: 4,
  },
  predictedHours: {
    color: '#fff',
    fontSize: 36,
    fontWeight: 'bold',
  },
  predictionLabel: {
    color: '#b8b8b8',
    fontSize: 14,
  },
  qualityBadge: {
    marginTop: 6,
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 12,
    backgroundColor: 'rgba(162, 89, 255, 0.15)',
    color: '#d0c5ff',
    fontWeight: '700',
    fontSize: 14,
  },
  riskBadge: {
    marginTop: 6,
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 12,
    backgroundColor: 'rgba(255, 159, 28, 0.18)',
    color: '#ffd79a',
    fontWeight: '700',
    fontSize: 14,
  },
  metaText: {
    color: '#9aa0c2',
    fontSize: 13,
    marginTop: 4,
  },
  factorsRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    marginTop: 12,
  },
  predictButtonFull: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#a259ff',
    paddingVertical: 12,
    borderRadius: 12,
    gap: 8,
    marginTop: 14,
  },
  factorChip: {
    backgroundColor: '#1a1a2e',
    paddingVertical: 8,
    paddingHorizontal: 12,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.05)',
  },
  factorLabel: {
    color: '#fff',
    fontSize: 13,
    fontWeight: '600',
  },
  factorImpact: {
    color: '#b8b8b8',
    fontSize: 12,
    marginTop: 2,
  },
  statsRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: 8,
    marginBottom: 12,
    gap: 10,
  },
  statTile: {
    flex: 1,
    backgroundColor: '#1a1a2e',
    borderRadius: 12,
    padding: 12,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.05)',
  },
  statValue: {
    color: '#fff',
    fontSize: 18,
    fontWeight: '700',
    marginTop: 6,
  },
  statLabel: {
    color: '#9aa0c2',
    fontSize: 13,
    marginTop: 2,
  },
  tipsList: {
    gap: 10,
  },
  tipRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  tipText: {
    color: '#cdd2f5',
    fontSize: 14,
    flex: 1,
    lineHeight: 20,
  },
});
